font-awesome upgraded for version 5
Darshan-Chauhan/ember-scroll-to-bottom pull request #1
Opened 2019-01-25 11:27 UTC by abulsayyad123

Hi @Darshan-Chauhan ,
I have upgraded font-awesome to version 5. Please review the PR and let me know if any change is required.
Thanks

2019-01-25 11:29 UTC, Darshan-Chauhan requested changes

2019-01-25 11:29 UTC, Darshan-Chauhan commented on app/templates/components/scroll-to-bottom.hbs
> +      <i class="fa fa-angle-double-down" aria-hidden="true">{{fa-icon 'angle-double-down'}}</i>
@abulsayyad123  can you keep the **<i>** tag and remove class from it?

2019-01-25 11:45 UTC, abulsayyad123 commented on app/templates/components/scroll-to-bottom.hbs
> +      <i class="fa fa-angle-double-down" aria-hidden="true">{{fa-icon 'angle-double-down'}}</i>
Removed 👍

2019-01-25 11:48 UTC, Darshan-Chauhan commented
@abulsayyad123 , remove `bower.json` file also

2019-01-28 04:13 UTC, Darshan-Chauhan approved these changes

2019-01-28 04:13 UTC, Darshan-Chauhan approved these changes

2019-01-28 04:13 UTC, merged